# -*- coding: utf-8 -*-
"""Running the app.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/154RIoYEy_5a1aVzbMw3l6R8C-0gW3mja
"""

!pip install -U scikit-learn
streamlit run streamlit_test.py