# -*- coding: utf-8 -*-
"""Streamlit-test.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ctypoInYRlaXmlnUOlK5lrLwom4kEzCs
"""

!pip install streamlit

"""
# My first app
Here's our first attempt at using data to create a table:
"""

import streamlit as st
import pandas as pd
df = pd.DataFrame({
  'first column': [1, 2, 3, 4],
  'second column': [10, 20, 30, 40]
})

df